# Generated by Django 5.1.4 on 2025-01-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
