# Generated by Django 5.1.4 on 2025-01-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_store', '0002_alter_media_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='size',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
