# Generated by Django 5.1.4 on 2025-01-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_store', '0003_alter_media_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='category',
            field=models.CharField(blank=True, choices=[('audio', 'Audio'), ('video', 'Video'), ('image', 'Image')], max_length=20),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
